### ISSUE TITLE
Feature Idea: QR-Code

### ISSUE THREAD

**Issue by Jisagi** [philmtd/full-house#22]
Hi, I was using another planing poker but switched to your version just recently and I really like it. The only feature I am missing, is a QR-Code to scan for an even possibility to join a session, especially on mobile devices.

I experimented with 2 different locations for the qrcode and wanted to know if you like the feature in general and which location you think would be best for it. The size of the qrcode can be adjusted as well. Below are 2 screenshots. The code for both options is already written, so I can create a pull request as soon as you give the go for a specific option. Feels free to let me know what you think or any suggestions you might have.

**Inside the invitation dialog**
![Inside the invitation dialog](https://i.imgur.com/uuwNYdf.png)

**Within the game screen**
The qrcode wil be hidden together with the other invitation elements as soon as 2+ users are present
![Within the game screen](https://i.imgur.com/ixtNQGK.png)

**Comment by philmtd** [comment]
Hi and thank you for your suggestion!

Just to make sure I understand your use case: I guess that you share the game on a beamer and everyone participating in the meeting joins with their phones. Did I get that right?

I'm not 100% convinced that this feature will be generally useful to most users. Until today the use cases I know are people who use the game from their computers without sharing a screen or beamer so the link needs to be shared in a chat or other communication tool. I don't know which browser you use but some browsers (Chrome, Brave, ?) have a built-in feature to generate a QR code to the currently open website. Would that already work for you?

In case you really need the feature built in:

I like the QR code in the dialog better because it aligns better with the UI. Having it in the dialog would also allow you to always re-show the QR code to someone wanting to join later when there are already more than two players in the game.

In case we need to implement this we'll also have to make sure it integrates well into the design and maybe only shows the QR code if the user explicitly requests it to keep the UI clean. I'll be happy to help in that case.

But first could you please check whether you use a browser that already supports generating QR codes and if that would work for you? Let me know :)

**Comment by Jisagi** [comment]
Hi, thanks for your long answer.

Use case: Yes, that is exactly how we used to use the old planning poker we had. The projekt lead had the website projected to the wall and everyone either joined with a number&letter code or on mobile with the QR-Code.

I have seen the the qr generation in chrome, but switched to firefox just recently, not sure if I have seen the feature there. I didn't look into that too deep though, so I might have missed it. It's mostly a convenience thing and for those, who aren't as tech savvy as others. I don't particularly NEED this feature, but I thought, it might be a neat addition, so I suggested it.

The argument for the dialog option ist absolutely valid, I didn't even think about it no reappearing despite me even noting it in the initial post. Therefore scratch the other option.

The implementation I went for was done with [angularx-qrcode](https://www.npmjs.com/package/angularx-qrcode), which is simple to use. Adding to what you said, the feature could be made optional globally maybe through the provided user config and even disabled in the default one. Different to that, a "show me a qrcode" button inside the invitation dialog could be an option as well, or a per-game toggle on creation.

When it comes to layout, I not a good frontend guy ;D I'd leave that to you. The code change for the generation is minimal and also uses "window.location.toString()" as input. The rest is just a <qrcode> element from the lib and a new line in the translation, that is it. I did not check how you implemented the global config, but I think that part is on the backend side of things, so a qr coding change would necessitate some kind of api change as well. The easiest option would therefore be something outside the config, maybe with the button or something, but you might have other ideas as well.

**Comment by philmtd** [comment]
I see. Yes I think Firefox does not have this built in... I will have a look at that library and think about how we could include this feature into the app. :)

**Comment by philmtd** [comment]
I created a first idea in #23. Would you mind to try it out and tell me whether it would fit your needs, @Jisagi?

**Comment by Jisagi** [comment]
This looks very nice and also does not intrude too much into the overall design. I never tried the config option for the lib, but did not think, such a clean look would be possible. I love it! If you like it, too, feel free to add this into the app.

![image](https://i.imgur.com/0PxQb01.png)

**Comment by philmtd** [comment]
Great. I just released it in version 1.3.0 (in case you use the Helm chart it's the chart version 1.2.1). Enjoy :)

**Comment by Jisagi** [comment]
Wonderful, thank you very much! I'm already running the latest version (using the docker version btw).
